# -*- coding: utf-8 -*-
"""Untitled10.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1eIhD5kb4NLhQalqenqG3Zsfuef7Yvk9R
"""

# Commented out IPython magic to ensure Python compatibility.
import pandas as pd
import seaborn as sns
import matplotlib.pyplot as plt
# % matplotlib inline

df=pd.read_csv('/content/drive/MyDrive/Lending_Club_Loan_approval_Optimization.csv',index_col=[0])

df.head()

df.shape

df.duplicated().sum()

df=df.drop_duplicates()

df.head()

sns.scatterplot(x="Risk_Score",y="Amount Requested",data=df,legend='auto')

corrmat = df.corr()
top_corr_features = corrmat.index
plt.figure(figsize=(10,10))
#plot heat map
g=sns.heatmap(df[top_corr_features].corr(),annot=True,cmap="RdYlGn")

X=df.iloc[:,:-1].values
y=df.iloc[:,-1].values

X

y

sns.countplot(y)

from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size = 0.20, random_state = 101)

X_train

from sklearn.preprocessing import StandardScaler
sc = StandardScaler()
X_train = sc.fit_transform(X_train)
X_test = sc.transform(X_test)

X_train

from sklearn.ensemble import GradientBoostingClassifier
classifier=GradientBoostingClassifier(random_state=101,n_estimators=200,learning_rate=0.05)
classifier.fit(X_train,y_train)

y_pred=classifier.predict(X_test)

from sklearn.metrics import classification_report
print(classification_report(y_test, y_pred))

import pickle
pickle.dump(classifier, open('model.pkl','wb'))

model = pickle.load(open('model.pkl','rb'))
print(model.predict([[3600.0,677.0, 5.91,10]]))